// Recontres
export const GET_RENCONTRES_SUCCESS = "GET_RENCONTRES_SUCCESS"
// Recontre
export const AJOUT_RENCONTRE = "AJOUT_RENCONTRE"
export const POST_RENCONTRE = "POST_RENCONTRE"
export const POST_RENCONTRE_SUCCESS = "POST_RENCONTRE_SUCCESS"
export const GET_RENCONTRE_SUCCESS = "GET_RENCONTRE_SUCCESS"
export const PUT_RENCONTRE_SUCCESS = "PUT_RENCONTRE_SUCCESS"
export const DELETE_RENCONTRE_SUCCESS = "DELETE_RENCONTRE_SUCCESS"
export const NOUVELLE_MARQUE = "NOUVELLE_MARQUE"
export const EDITER_RENCONTRE = "EDITER_RENCONTRE"
export const NOUVELLE = "NOUVELLE"
export const AJOUTER_RENCONTRE = "AJOUTER_RENCONTRE"
export const NOUVELLE_PERIODE = "NOUVELLE_PERIODE"
